account/urls.py
from . import views
from django.urls import path, include


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('users/', views.user_list, name='user_list'),
    path('users/<username>/', views.user_detail, name='user_detail')
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('social_auth/', include('social_django.urls', namespace="social")),
    path('images/', include('images.urls', namespace='images'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = "images"

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('details/<int:id>/<slug:slug>/', views.image_detail, name='image_detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list')
    ]

account/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateTimeField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f'Profile for {self.user.username}'


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user_from} follows {self.user_to}'


# Add following fields to user dynamically
user_model = get_user_model()
user_model.add_to_class('following',
                        models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data['password'] != data['password2']:
            raise forms.ValidationError("Passwords do not match")
        return data['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_birth', 'photo')

account/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm, UserEditForm, ProfileEditForm
from .models import Profile
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User


# Create your views here.
# def user_login(request):
#     if request.method == 'POST':
#         login_form = LoginForm(request.POST)

#         if login_form.is_valid():
#             data = login_form.cleaned_data
#             user = authenticate(request,
#                                 username=data['username'],
#                                 password=data['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request,user)
#                     return HttpResponse('Authenticated successfully')
#                 else:
#                     return HttpResponse('Disabled account')
#             else:
#                 return HttpResponse("Invalid login")
#     else:
#         login_form = LoginForm()
#     return render(request, 'account/login.html', {'form': login_form})


@login_required
def dashboard(request):
    return render(request, 'account/dashboard.html', {'section': 'dashboard'})


def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)  # creates an empty profile when a user signs up
            return render(request, 'account/register_done.html', {'user': new_user})
    else:
        form = UserRegistrationForm()
    return render(request, 'account/register.html', {'register_form': form})


@login_required
def edit(request):
    changed = False
    if request.method == "POST":
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile updated successfully')
            changed = True
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'account/edit.html', {'user_form': user_form,
                                                 'profile_form': profile_form,
                                                 'changed': changed
                                                 })


@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'account/user/user_list.html', {'section': 'people', 'users': users})


@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, 'account/user/detail.html', {'section': 'people', 'user': user})

account/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8" name="bookmarks" content="bookmarks">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Asap:400,700" rel="stylesheet" type="text/css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2.2.1/src/ js.cookie.min.js"></script>
  <script>
      let csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
       // these HTTP methods do not require CSRF protection
       return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
     }
     $.ajaxSetup({
       beforeSend: function(xhr, settings) {
         if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
           xhr.setRequestHeader("X-CSRFToken", csrftoken);
} }
});
      $(document).ready(function() {
          {% block domready %}
          {% endblock %}
      })
  </script>
  <body style="font-family: 'Asap', 'Montserrat';">

      <nav class="navbar navbar-expand-md navbar-dark bg-primary sticky-top mb-4">
          <a class="navbar-brand" href="{% url 'dashboard' %}" style="font-family: 'Asap';">Bookmarks</a>
          <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
              aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          <div class="collapse navbar-collapse" id="collapsibleNavId">

              {% if request.user.is_authenticated %}
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                  <li {% if section == 'dashboard' %} class="nav-item active" {% else %} class="nav-item"  {% endif %}>
                      <a class="nav-link" href="{% url 'dashboard' %}">Dashboard <span class="sr-only">(current)</span></a>
                  </li>

                  <li {% if section == 'images' %} class="nav-item active" {% else %} class="nav-item"  {% endif %}>
                      <a class="nav-link" href="{% url 'images:list' %}">Images</a>
                  </li>

                  <li {% if section == 'people' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
                    <a class="nav-link" href="{% url 'user_list' %}">People</a>
                </li>
              </ul>
              {% endif %}

              <span class="my-2 my-lg-0 text-white">
                {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name }}
              </span>
                <div class="dropdown dropdown-left mx-4">
                  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                     Settings
                  </button>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
                    <a class="dropdown-item" href="{% url 'password_reset' %}">Reset password</a>
                    <a class="dropdown-item" href="{% url 'edit' %}">edit profile</a>
                  </div>
                </div>
                {% endif %}
                
          </div>
      </nav>

      {% if messages %}

        {% for message in messages %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
          </button>
          {{ message|safe }}
        </div>
        {% endfor %}

      {% endif %}

      <div class="container content">
          {% block content %}
          {% endblock %}
      </div>

      <div class="container-fluid mb-0  bg-primary text-white">
          {% block footer %}
          {% endblock %}
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://use.fontawesome.com/3ced957014.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>